# Generated by Django 3.1.14 on 2022-11-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Train number')),
                ('travel_times', models.PositiveSmallIntegerField(verbose_name='Travel Time')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_set_rotes_model', to='cities.city', verbose_name='arrival city_rotes_model')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_set_rotes_model', to='cities.city', verbose_name='departure city_rotes_model')),
                ('trains', models.ManyToManyField(to='trains.Trains', verbose_name='trains list')),
            ],
            options={
                'ordering': ['travel_times'],
            },
        ),
    ]
